services:
  picarx-gazebo:
    build:
      context: Dockerfile
      dockerfile: ./simulation
      target: tests
    image: abarbie/picarx/picarx-gazebo:${TAG}
    env_file:
      - ./core/dtp/env/simulation.env
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=0
      - ROS_HOSTNAME=picarx-gazebo
    tty: true
    ports:
      - 11312:11312
    volumes:
      - ./core:/root/catkin_ws/src/core
      - ./simulation:/root/catkin_ws/src/simulation
    command: /bin/bash -c "roslaunch picarx_gazebo picarx-world.launch & roslaunch picarx_control picarx_control.launch & source install/setup.bash ; sleep 30 ; python3 src/simulation/picarx_control/tests/steering_integration_test.py"
    healthcheck:
      test: [ "CMD-SHELL", "curl $${ROS_MASTER_URI} || exit 1" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 1s

  shadow-dtp:
    image: abarbie/picarx:${TAG:-latest}
    env_file:
      - ./core/dtp/env/simulation.env
    tty: true
    command: /bin/bash -c "roslaunch arches_core digitalshadow_pt.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  mqtt-dtp:
    image: abarbie/picarx/arches-mqtt-bridge:${TAG}
    build:
      dockerfile: Dockerfile-arches-mqtt-bridge
      context: ./ros
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH}
    env_file:
      - ./core/dtp/env/simulation.env
    tty: true
    command: /bin/bash -c "roslaunch arches_mqtt_bridge pt_client.launch host:=mqtt-server"
    depends_on:
      picarx-dt:
        condition: service_healthy

  motor_left-dtp:
    build:
      dockerfile: Dockerfile
      context: ./ros/drivers/dcmotor/
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH}
    image: abarbie/picarx/drivers/dcmotor:${TAG}
    env_file:
      - ./core/dtp/env/simulation.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/drivers/dcmotor:/root/catkin_ws/src/drivers/dcmotor
    command: /bin/bash -c "roslaunch picarx_dcmotor_driver dcmotor_left.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  motor_right-dtp:
    image: abarbie/picarx/drivers/dcmotor:${TAG}
    tty: true
    env_file:
      - ./core/dtp/env/simulation.env
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/drivers/dcmotor:/root/catkin_ws/src/drivers/dcmotor
    command: /bin/bash -c "roslaunch picarx_dcmotor_driver dcmotor_right.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  steering-dtp:
    image: abarbie/picarx/drivers/clutchgear:${TAG}
    build:
      dockerfile: Dockerfile
      context: ./ros/drivers/clutchgear
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH}
    env_file:
      - ./core/dtp/env/simulation.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/drivers/clutchgear:/root/catkin_ws/src/drivers/clutchgear
    command: /bin/bash -c "roslaunch picarx_clutchgear_driver ackermann_clutchgear_driver.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  ackermann_skill-dtp:
    image: abarbie/picarx/skills/ackermann_drive:${TAG}
    build:
      dockerfile: Dockerfile
      context: ./ros/skills/ackermann_drive
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH}    
    env_file:
      - ./core/dtp/env/simulation.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/skills/ackermann_drive:/root/catkin_ws/src/skills/ackermann_drive
    command: /bin/bash -c "roslaunch picarx_ackermann_drive ackermann_skill.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  motor_emulator_left-dtp:
    image: abarbie/picarx/emulators/dcmotor:${TAG}
    build:
      dockerfile: Dockerfile
      context: ./ros/emulators/dcmotor
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH}
    env_file:
      - ./core/dtp/env/simulation.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/emulators/dcmotor:/root/catkin_ws/src/emulators/dcmotor
    command: /bin/bash -c "roslaunch picarx_dcmotor_emulator dcmotor_emulator_left.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  motor_emulator_right-dtp:
    image: abarbie/picarx/emulators/dcmotor:${TAG}
    env_file:
      - ./core/dtp/env/simulation.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/emulators/dcmotor:/root/catkin_ws/src/emulators/dcmotor
    command: /bin/bash -c "roslaunch picarx_dcmotor_emulator dcmotor_emulator_right.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  steering_emulator-dtp:
    image: abarbie/picarx/emulators/clutchgear:${TAG}
    build:
      dockerfile: Dockerfile
      context: ./ros/emulators/clutchgear
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH}
    env_file:
      - ./core/dtp/env/simulation.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/emulators/clutchgear:/root/catkin_ws/src/emulators/clutchgear
    command: /bin/bash -c "roslaunch picarx_clutchgear_emulator ackermann_clutchgear_emulator.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

networks:
  picarx:
    external: true
