name: PiCar-X Main Build

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - uses: actions/checkout@v2

    - name: Build with Docker Compose
      working-directory: ./PiCar-X
      run: |
        TAG=${{github.ref_name:-latest}}-arm64v8 ARCH=arm64v8 docker compose -f docker-compose-core.yml build --no-cache
        TAG=${{github.ref_name:-latest}}-arm64v8 docker compose -f docker-compose-dtp.yml build --no-cache

#    - name: Run pytest in Docker container
#      run: |
#        docker-compose -f docker-compose-core.yml run --rm app pytest

#    - name: Start roslaunch in Docker container
#      run: |
#        docker-compose -f docker-compose-core.yml run --rm app roslaunch

    - name: Push to Docker Hub
      working-directory: ./PiCar-X
      run: |
        TAG=${{ github.ref_name:-latest }}-arm64v8 docker compose -f docker-compose-dtp.yml push